### ISSUE TITLE
specific iso

### ISSUE THREAD

**Issue by edison658** [Qubits01/xbox_shrinker#4] opened 2022-03-12 17:10 UTC
Hello, this does not seem to work with games like :
Tony Hawk's American Wasteland (USA, Europe) (En,Fr,De,Es,It)
crc="d1d346b0" md5="abb7aa47ffda665f564e96fe996a00e4" sha1="fdbe1fb30d4f3355d424fd1892d391fa47f0752a"

TOCA Race Driver 3 (USA, Europe) (En,Fr,De,Es,It) 
crc="445dfded" md5="8699463fee14c11614323a271cf6a04e" sha1="f6fff0e7fb183f82851cb12fde7c67c2ec1d6e2d"

**Comment by Qubits01** [comment] 2022-03-12 22:42
Seems to work fine here. What error message do you get?

**Comment by edison658** [comment] 2022-03-13 07:59
No error message but nothing happens
no creation of *.iso.dec or *.rc4 file

Calculating hash and getting Security Sector Ranges from iso... then close

**Comment by Qubits01** [comment] 2022-03-13 17:39
OK, I confirmed a problem. It does show an error though.
There seems to be a problem with the detection of the SS ranges of some titles, including the ones you mentioned. Will look into it and hopefully post a fix soon.

**Comment by Qubits01** [comment] 2022-03-14 11:45
Issue should be fixed now.  
Tested with `Tony Hawk's American Wasteland (USA, Europe) (En,Fr,De,Es,It)` and should work for all other cases with the same issue.

**Comment by edison658** [comment] 2022-03-14 18:59
shrinking Tony Hawk's American Wasteland (USA, Europe) (En,Fr,De,Es,It) works

shrinking TOCA Race Driver 3 (USA, Europe) (En,Fr,De,Es,It) not working

**Comment by Qubits01** [comment] 2022-03-14 23:53
I'll take a look. Must be a different type of issue then

**Comment by Qubits01** [comment] 2022-03-15 00:21
I confirmed it works with `TOCA Race Driver 3 (USA, Europe) (En,Fr,De,Es,It)` as expected.
Please double check that the checksum of your file that it matches the redump/dat entry that you posted above.

If you need further help, execute xbox_shrinker on the command line, so the terminal window does not automatically close when the programs exits. xbox_shrinker should produce a error message for trouble shooting like it did with Tony Hawk's which you also did not see, probably because of the terminal window closing automatically.

**Comment by edison658** [comment] 2022-03-15 16:40
Yes, you're right. I can confirm it works.
My rar extraction was faulty.
Re extract archive( then compare crc match with redump) then decrypt is ok in very few seconds

Very powerful utility. Mega Thanks

**Closed as completed** 2022-03-16 08:57 UTC
